@startuml
object c1:Circulo {
+ Color = "Negro"
+ Diámetro = 1

}

object r1:Rectángulo {
+ Longitud = 3
+ Anchura = 1
+ Color = "Naranja"
}

object c2:Cuadrado {
+ Longitud = 1.5
+ Color = "Azul"
}

object e1:Elipse {
+ Color = "Amarillo"
+ Eje Mayor = 3
+ Eje Menor = 1

}
@enduml