@startuml
class Cuadro implements Lugar1{
  -Titulo = "La Gioconda"
  -AC = "1503 - 1516" 
  -Tecnica = Óleo
  -Sub-técnica = Sfumato
  -Soporte = Madera de álamo
  -Autor = "Leonardo da Vinci"
  -Estado de conversion = Regular


}
class Replica extends Cuadro implements Lugar2{
  -Titulo = "La Gioconda"
  -AC = "1503 - 1516" 
  -Tecnica = Óleo
  -Sub-técnica = Pincelada simple
  -Soporte = Madera de nogal
  -Autor = desconocido
  -Estado de conversion = Regular

}
Interface Lugar1{

  - Institucion = "Museo de El Prado"
  - Ciudad = "Paris"
  - País = "Francia"


}
Interface Lugar2{

  - Institucion = "Museo de El Prado"
  - Ciudad = "Madrid"
  - País = "España"


}

@enduml

"https://www.plantuml.com/plantuml/svg/jP71QXin443l-ehftWrT5_TMS35kCTYmrANtiJJU2hIQPII5X92lo1Vac4CE-ORziKYxIGWX9X38zStCldre6I9AJ9rJN-9_wWZqnO6bLTfX2B1AQ8J1ThtBCny3R5EBKbygWDbV6vDZ-07L5k6tPStUO5KcFrU5reklts06zQB-Ni5uGDfRZNasN3lYWlRfC8l3xHFV7rE7SPfmpn8fmnqQ4WH3CDmux7WqfCWogeazYc4m2F-irtRyWNMkAYpdi3yZ2PPztlv3RN8eIgchAJ2JtXKrdKVovcJm_BE26-irEJG8ONIUAlVSediPRYXaFMjh-FtWqhlnaUI8cfwViDp1neUOi_IqN-rIeF4pQmUDeE4n3rOs6JHbeK6nOO8D3dUXi5-2Nbkir1kU-GSzELsiUILQXnw7-qUHMf8tgNCF"