@startuml
class Cuadro implements Lugar1{
  -Titulo = "La Gioconda"
  -AC = "1503 - 1516" 
  -Tecnica = Óleo
  -Sub-técnica = Sfumato
  -Soporte = Madera de álamo
  -Autor = "Leonardo da Vinci"
  -Estado de conversion = Regular


}
class Replica extends Cuadro implements Lugar2{
  -Titulo = "La Gioconda"
  -AC = "1503 - 1516" 
  -Tecnica = Óleo
  -Sub-técnica = Pincelada simple
  -Soporte = Madera de nogal
  -Autor = desconocido
  -Estado de conversion = Regular

}
Interface Lugar1{

  - Institucion = "Museo de El Prado"
  - Ciudad = "Paris"
  - País = "Francia"


}
Interface Lugar2{

  - Institucion = "Museo de El Prado"
  - Ciudad = "Madrid"
  - País = "España"


}

@enduml
