@startuml
skinparam groupInheritance 2
 class FormaA{
   Color: 1Texto     
}
 class Cuadrilátero{
   Longitud : 1 Número    
}
 class Rectangulo{
   Anchura : 1 Número
}
 class Cuadrado{
   Null
}
 class Cónica{
  Null
}
 class Circulo{
  Diámetro: 1 Número
}
 class Elipse{
  Eje Mayor: 1 Número
  Eje Menor: 1 Número
}
FormaA <|-- Cuadrilátero
FormaA <|-- Cónica
Cuadrilátero <|-- Rectangulo
Cuadrilátero <|-- Cuadrado
Cónica <|-- Circulo
Cónica <|-- Elipse

@enduml

