@startuml
class Proyecto {
+ Nombre : String
+ Fecha de inicio: Date
+ Fecha de fin: Date
}

class Miembro_del_Equipo as "Persona"{
+ Nombre : String
+ Apellidos: String
+ Rol: String
}

class Lugar_de_Actuación {
+ Nombre : String
+ Coordenada X: Double
+ Coordenada Y: Double
}

Miembro_del_Equipo "1--*" - "0--*" Proyecto : Participa

Proyecto "0--*" - "0--*" Lugar_de_Actuación: Tiene lugar en

@enduml