@startuml
class Persona{
    Nombre: 1 Texto
    Primer apellido: 1 Texto
    Segundo apellido: 0..1 Texto
    Fecha denacimiento: 1 Tiempo
    Sexo: 1 Texto
    Número de identificación: 0..1 Texto
}

Persona -- Persona: > Está casada con (cónyuge)
Persona -- Persona: > Es hija de (progenitor)