@startuml
skinparam groupInheritance 2
class EntidadGeografica{
 codigo: 1 Texto
 Nombre: 1 Texto
}
entity Punto
entity Linea
entity Area

entity puntos{
 X: 1 Numero
 Y: 1 Numero
 Z: 1 Numero
}
entity lineas{
 linea: 2 Puntos
}
entity Areas{
 Area: 3 Puntos
}

puntos"2..*" --o "0..*"lineas
puntos"3..*" --o "0..*"Areas
EntidadGeografica <|-- Punto
EntidadGeografica <|-- Linea
EntidadGeografica <|-- Area

@enduml
